# iptables-multiport не поддерживает protocol=all — используем iptables-allports.
[asterisk]
enabled  = true
port     = 5060,5061
filter   = asterisk
action   = iptables-allports[name=asterisk, protocol=all]
logpath  = /var/log/asterisk/messages
maxretry = 4
