[DEFAULT]
# 4 неудачных попытки за 10 минут → бан на 10 минут
maxretry   = 4
findtime   = 10m
bantime    = 10m
banaction  = iptables-multiport

# Не банить локальные адреса
ignoreip   = 127.0.0.1/8 ::1
