[phpmyadmin]
enabled  = true
filter   = nginx-phpmyadmin
port     = 8090,8443
action   = iptables-multiport[name=phpmyadmin, port="8090,8443", protocol=tcp]
logpath  = /var/log/nginx/access.log
maxretry = 4

# Защита от неверных HTTP-credentials на уровне Nginx
[nginx-http-auth]
enabled  = true
filter   = nginx-http-auth
action   = iptables-multiport[name=nginx, port="8090,8443", protocol=tcp]
logpath  = /var/log/nginx/error.log
maxretry = 4
