[transport-udp]
type = transport
protocol = udp
bind = 0.0.0.0

[1000]
type = endpoint
context = default
disallow = all
allow = alaw        ; G.711 A-law
allow = opus        ; Opus кодек
auth = 1000
aors = 1000

[1000]
type = auth
auth_type = userpass
password = 123456
username = 1000

[1000]
type = aor
max_contacts = 1

[2000]
type = endpoint
context = default
disallow = all
allow = alaw        ; G.711 A-law
allow = opus        ; Opus кодек
auth = 2000
aors = 2000

[2000]
type = auth
auth_type = userpass
password = 123456
username = 2000

[2000]
type = aor
max_contacts = 1
