[settings]
ps_endpoints => odbc,asteriskdb,ps_endpoints
ps_auths     => odbc,asteriskdb,ps_auths
ps_aors      => odbc,asteriskdb,ps_aors
ps_contacts  => odbc,asteriskdb,ps_contacts
extensions   => odbc,asteriskdb,extensions
