[settings]
ps_endpoints => odbc,asteriskdb,ps_endpoints
ps_auths => odbc,asteriskdb,ps_auths
ps_aors => odbc,asteriskdb,ps_aors
ps_endpoint_id_ips => odbc,asteriskdb,ps_endpoint_id_ips
extensions => odbc,asteriskdb,extensions
iaxfriends => odbc,asteriskdb,iaxfriends
ps_outbound_publishes => odbc,asteriskdb
ps_inbound_publications = odbc,asteriskdb
ps_asterisk_publications = odbc,asteriskdb
ps_contacts => odbc,asteriskdb,ps_contacts
